------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
	output = "",
	mode = "preferred",
	position = "auto",
	scale = "auto",
})

-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

require("keybinds")
require("autostart")
-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
--hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Load dynamic colors from Stylix (generated by Home Manager)
local has_colors, colors = pcall(dofile, os.getenv("HOME") .. "/.config/dynamic-colors/hypr.lua")
local active_border_1 = has_colors and colors.active_border_1 or "rgba(c87f3eee)"
local active_border_2 = has_colors and colors.active_border_2 or "rgba(b18a59ee)"
local inactive_border = has_colors and colors.inactive_border or "rgba(14141d88)"

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
	general = {
		gaps_in = 3,
		gaps_out = 2,

		border_size = 2,

		col = {
			-- Active: dynamic stylix accent gradient
			active_border = { colors = { active_border_1, active_border_2 }, angle = 45 },
			-- Inactive: subtle dynamic dark grey
			inactive_border = inactive_border,
		},

		-- Set to true to enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = true,

		-- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
		allow_tearing = false,

		layout = "dwindle",
	},

	decoration = {
		rounding = 16,
		rounding_power = 2,

		-- Crystal UI transparency for windows
		active_opacity = 0.93,
		inactive_opacity = 0.85,

		shadow = {
			enabled = true,
			range = 20,
			render_power = 4,
			color = 0x44000000,
		},

		-- Liquid macOS-style multi-pass frosted glass blur
		blur = {
			enabled = true,
			size = 8,
			passes = 3,
			new_optimizations = true,
			ignore_opacity = true,
			xray = false,
			noise = 0.02,
			contrast = 0.95,
			brightness = 0.90,
			vibrancy = 0.25,
		},
	},

	animations = {
		enabled = true,
	},
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

-- Default springs
hl.curve("easy", { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

-- Animation Speed Scale (1 to 10)
-- 10 = Fastest, 1 = Slowest
local anim_scale = 8
local a = 10 / anim_scale -- multiplier (lower speed value = faster animation)

hl.animation({ leaf = "global", enabled = true, speed = 5 * a, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 2.7 * a, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 2.4 * a, spring = "easy" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 2.0 * a, spring = "easy", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.0 * a, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.0 * a, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.0 * a, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 1.5 * a, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 1.9 * a, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 2.0 * a, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.0 * a, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.0 * a, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.0 * a, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.5 * a, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.0 * a, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.5 * a, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 2, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 2, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding = 16,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding = 16,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
	dwindle = {
		preserve_split = true, -- You probably want this
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
	master = {
		new_status = "master",
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
	scrolling = {
		fullscreen_on_one_column = true,
	},
})

----------------
----  MISC  ----
----------------

hl.config({
	misc = {
		force_default_wallpaper = -1, -- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = true, -- If true disables the random hyprland logo / anime girl background. :(
	},
})

---------------
---- INPUT ----
---------------

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",

		follow_mouse = 1,

		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

		touchpad = {
			natural_scroll = true,
		},
	},
})

hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
	-- Ignore maximize requests from all apps. You'll probably like this.
	name = "suppress-maximize-events",
	match = { class = ".*" },

	suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
	-- Fix some dragging issues with XWayland
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},

	no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
	name = "move-hyprland-run",
	match = { class = "hyprland-run" },

	move = "20 monitor_h-120",
	float = true,
})

hl.window_rule({
	name = "pavucontrol-glass",
	match = { class = "pavucontrol" },
	float = true,
	opacity = "0.75 0.75",
	pin = true,
	size = "500 400",
})

-- Material/macOS floating windows for Waybar interactive dialogs
hl.window_rule({
	name = "pavucontrol-float",
	match = { class = "org.pulseaudio.pavucontrol" },
	float = true,
	size = "680 500",
	center = true,
})

hl.window_rule({
	name = "pavucontrol-legacy-float",
	match = { class = "pavucontrol" },
	float = true,
	size = "680 500",
	center = true,
})

hl.window_rule({
	name = "nm-connection-editor-float",
	match = { class = "nm-connection-editor" },
	float = true,
	size = "700 520",
	center = true,
})

hl.window_rule({
	name = "blueman-manager-float",
	match = { class = "blueman-manager" },
	float = true,
	size = "650 480",
	center = true,
})

-- EWW Applet Layer Rules (popups float above bar, no border/shadow)
hl.layer_rule({
	name = "eww-volume-popup",
	match = { namespace = "volume-popup" },
	animation = "fade",
	blur = true,
})

hl.layer_rule({
	name = "waybar-blur",
	match = { namespace = "waybar" },
	blur = true,
	ignore_alpha = 0.0,
})

hl.layer_rule({
	name = "wlogout-blur",
	match = { namespace = "logout_dialog" },
	blur = true,
	ignore_alpha = 0.0,
})

hl.layer_rule({
	name = "rofi-blur",
	match = { namespace = "rofi" },
	blur = true,
	ignore_alpha = 0.0,
})

hl.layer_rule({
	name  = "orbit-blur",
	match = { namespace = "orbit" },
	blur  = true,
	ignore_alpha = 0.0,
	animation = "fade",
})

hl.window_rule({
	name = "picture-in-picture",
	match = { title = "^Picture-in-Picture$" },
	float = true,
	pin = true,
})

hl.layer_rule({
	name = "swaync-blur",
	match = { namespace = "swaync-control-center" },
	blur = true,
	ignore_alpha = 0.0,
})

hl.layer_rule({
	name = "swaync-notification-blur",
	match = { namespace = "swaync-notification-window" },
	blur = true,
	ignore_alpha = 0.1,
})

hl.window_rule({
	name = "control-center-float",
	match = { class = "ControlCenter" },
	float = true,
	size = "720 700",
	center = true,
})
